"use client";

import Link from "next/link";
import { useState, useEffect } from "react";

// Hand-picked pieces for the homepage rotation, by v3 inscription id.
//
// These load straight from the chain rather than from a bundled copy of the
// engine. The v3 engine carries no data at all — each piece reads its own
// dataset from /r/metadata and finds its siblings via /r/children — so it can
// only render where those endpoints exist. A copy served from this site would
// hold black. Pointing at an ord gateway shows the real artifact and cannot go
// stale; the bundled engine that used to live in public/ was already three
// versions behind, including the canvas-sizing bug.
//
// ids regenerated by cessation/sync-tracker.mjs — never transcribe them by hand.
const FEATURED_PIECES = [
  "35e961c5f4003a9e064db70e6d1c55b7314ce4b38413d3d93a32b116c748122fi0", // 00 — 2018-07-16
  "4df18c747f730fd37d5a3db9e7dccf547e4cba239a2bdd24d9deaff49b3ffdb1i0", // 06 — 2020-02-28
  "4deca53568108cdea23e3eb1eb0e31ce3c55d64bb80f53f57ce17b56da5215f5i0", // 10
  "8613cf254fa05cb45208c84d448d10096f622cb6685f8ccaad99f7a435b334e8i0", // 17
  "b960b347890805fadd0c51c16de143c392ed261f727c0f81bc0fe4c8e68f4ce0i0", // 18
  "6b1284313b2b1d8a272322f9c5f8304c8ec40bd1493a38da6e8b3e00b3e60d23i0", // 22
  "6f54436e26406591be11924d1b10fcc8ce54395ddd7f8189a97f08947fc0e36di0", // 24
  "11bd3cc8601a4e19d6242469ab82a30f1c0ae28555b59cc37fc9f08498c45f34i0", // 27
  "40b914134170dc5f9220642eb3f4d0ea7cea5c18e7e39655560f08508251d044i0", // 30 — 2026-09-18
];

export default function Home() {
  const [pieceSrc, setPieceSrc] = useState("");
  useEffect(() => {
    const id = FEATURED_PIECES[Math.floor(Math.random() * FEATURED_PIECES.length)];
    // No params needed: each piece's own on-chain HTML already carries
    // t/ht/unix/hue/block on the script tag that loads the engine.
    setPieceSrc(`https://ordinals.com/content/${id}`);
  }, []);

  return (
    <>
      <style>{`
        @media (max-width: 768px) {
          .home-grid { grid-template-columns: 1fr !important; }
          .home-piece { order: -1; }
        }
      `}</style>

      <div
        className="home-grid"
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 3fr",
          gap: "60px",
          alignItems: "center",
          minHeight: "calc(100vh - 120px)",
        }}
      >
        <div>
          <h1
            style={{
              fontSize: "clamp(24px, 5vw, 64px)",
              fontWeight: "400",
              lineHeight: "1",
              letterSpacing: "-0.02em",
              color: "var(--fg)",
              marginBottom: "20px",
            }}
          >
            Cessation
          </h1>

          <p
            style={{
              fontSize: "14px",
              color: "var(--muted)",
              lineHeight: "1.7",
              marginBottom: "32px",
            }}
          >
            A generative art self-portrait series inscribed on the Bitcoin
            blockchain, in which each piece evolves over multiple lifespans.
            Each new portrait starts its journey as an archive of the
            body&apos;s current state.
          </p>

          <Link
            href="https://cessation-tracker.vercel.app"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              fontSize: "13px",
              color: "var(--muted)",
              display: "inline-flex",
              alignItems: "center",
              gap: "6px",
            }}
            className="view-link"
          >
            View collection
            <span style={{ fontSize: "16px", lineHeight: 1 }}>→</span>
          </Link>
        </div>

        {/* Square, because that is the engine's own geometry: it sizes its
            container to min(100vw,100vh) and centres a 3:2 canvas inside a
            proportional black border. A wide box would leave the piece
            left-aligned with dead space beside it. Capped against viewport
            height so the square cannot outgrow the fold. */}
        <div
          className="home-piece"
          style={{ position: "relative", width: "100%", maxWidth: "min(100%, 62vh)", marginInline: "auto" }}
        >
          <div style={{ paddingBottom: "100%" }} />
          <iframe
            src={pieceSrc || undefined}
            title="Cessation"
            loading="lazy"
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              height: "100%",
              border: "none",
              display: "block",
            }}
          />
        </div>
      </div>
    </>
  );
}
